### ISSUE TITLE
编译好的efi文件无法运行

### ISSUE THREAD

**Issue by ilcpm** [acdzh/TC_UEFI_Project-2048#1]
你好，我用你提供的efi文件在UEFI下启动，通过grub的chainloader实现，也尝试过通过xorboot进行启动，都无法运行，一闪而过，没有任何提示，又尝试了使用QEMU模拟启动，同样也无法启动
请问是需要什么特定的环境才能运行吗

我把GitHub上能够直接搜索并提供efi文件的efi游戏都试了一下，一共5个游戏，只有两个可以运行，分别是[FlappyBirdy](https://github.com/hymen81/UEFI-Game-FlappyBirdy)和[俄罗斯方块](https://github.com/a1ive/uefi-tetris)，另外的两个贪吃蛇和一个迷宫也是无法运行

希望能知道无法运行的原因😂

**Comment by acdzh** [comment]
我只在 qemu 中测试过 (即直接 build run ), 没有在实机测试. 你有试过 readme 里的编译运行方式吗?
另外我的 EDK 版本是 [UDK2018](https://codeload.github.com/tianocore/edk2/zip/vUDK2018), 或许我搭建环境的方式有些不同? [https://www.cnblogs.com/acdzh/p/uefi_1_edk2.html](https://www.cnblogs.com/acdzh/p/uefi_1_edk2.html)

另外你看下[这个项目](https://github.com/kurtqiao/MyPkg)可以运行吗? 我的项目有一部分是来自于这个.

**Comment by ilcpm** [comment]
我不是搞开发的，没有开发环境，也不会搞这些😂
最近在研究系统启动，听说有用efi文件做游戏的，就想找几个来试试，单纯满足好奇心而已
我用的QEMU启动是直接一个EXE然后模拟真机启动的那种用来测试U盘能不能启动电脑的版本，所以可能对这种没有单独做过相关支持的文件进行运行
我们这种启动都是老老实实按照主板的要求，在U盘第一个FAT分区的EFI/Boot/文件夹下，64位的就启动bootx64.efi，32位就启动bootia32.efi，但是我各种方式都试了，也尝试过用其他的efi文件来启动这个efi都不行
我觉得可能就是类似于缺少“驱动”这样的问题吧，导致主板不能够执行
不打算在这个问题上纠结了，本来就是好奇而已
总之还是谢谢你热心的回复，超棒！

**Comment by acdzh** [comment]
单文件不行的😂
